/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:17:38 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Roles` CASCADE
;

/* Create Tables */

CREATE TABLE `Roles`
(
	`Role` VARCHAR(30) NOT NULL,
	`RoleName` VARCHAR(100) 	 NULL,
	`Description` TEXT 	 NULL,
	`Deleted` TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT `PK_Role` PRIMARY KEY (`Role` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Roles` 
 ADD INDEX `IDX_Deleted` (`Deleted` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;