/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:37:14 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `RolesAcl` CASCADE
;

/* Create Tables */

CREATE TABLE `RolesAcl`
(
	`AclID` INT NOT NULL AUTO_INCREMENT,
	`Role` VARCHAR(30) NOT NULL,
	`Resource` VARCHAR(100) NOT NULL,
	`Allow` VARCHAR(255) 	 NULL,
	`Deny` VARCHAR(255) 	 NULL,
	CONSTRAINT `PK_RolesAcl` PRIMARY KEY (`AclID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `RolesAcl` 
 ADD INDEX `IXFK_RolesAcl_Roles` (`Role` ASC)
;

ALTER TABLE `RolesAcl` 
 ADD INDEX `IDX_RolesAcl_Resource` (`Resource` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `RolesAcl` 
 ADD CONSTRAINT `FK_RolesAcl_Roles`
	FOREIGN KEY (`Role`) REFERENCES `Roles` (`Role`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;