/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:17:38 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Users` CASCADE
;

/* Create Tables */

CREATE TABLE `Users`
(
	`UserID` INTEGER NOT NULL AUTO_INCREMENT,
	`FullName` VARCHAR(255) 	 NULL,
	`UserName` VARCHAR(50) NOT NULL,
	`PwHash` VARCHAR(200) NOT NULL,
	`Email` VARCHAR(255) NOT NULL,
	`Phone` VARCHAR(255) 	 NULL,
	`Title` VARCHAR(100) 	 NULL,
	`Language` VARCHAR(10) 	 NULL,
	`Thumbnail` TEXT 	 NULL,
	`PwToken` VARCHAR(255) 	 NULL,
	`PwTokenExpire` DATETIME 	 NULL,
	`Created` DATETIME 	 NULL,
	`LastLogged` DATETIME 	 NULL,
	`Disabled` TINYINT NOT NULL DEFAULT 0,
	`Deleted` TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT `PK_Users` PRIMARY KEY (`UserID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Users` 
 ADD INDEX `IDX_Deleted` (`Deleted` ASC)
;

ALTER TABLE `Users` 
 ADD INDEX `IDX_UserName` (`UserName` ASC)
;

ALTER TABLE `Users` 
 ADD INDEX `IDX_PwToken` (`PwToken` ASC)
;

ALTER TABLE `Users` 
 ADD INDEX `IDX_Disabled` (`Disabled` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;