/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:17:38 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `UsersRoles` CASCADE
;

/* Create Tables */

CREATE TABLE `UsersRoles`
(
	`UserID` INTEGER NOT NULL,
	`Role` VARCHAR(30) NOT NULL,
	CONSTRAINT `PK_UsersRole` PRIMARY KEY (`UserID` ASC, `Role` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `UsersRoles` 
 ADD INDEX `IXFK_UsersRole_Role` (`Role` ASC)
;

ALTER TABLE `UsersRoles` 
 ADD INDEX `IXFK_UsersRole_Users` (`UserID` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `UsersRoles` 
 ADD CONSTRAINT `FK_UsersRole_Role`
	FOREIGN KEY (`Role`) REFERENCES `Roles` (`Role`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `UsersRoles` 
 ADD CONSTRAINT `FK_UsersRole_Users`
	FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;