/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:17:38 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `UsersAuthDrivers` CASCADE
;

/* Create Tables */

CREATE TABLE `UsersAuthDrivers`
(
	`UserID` INTEGER NOT NULL,
	`AuthDriver` VARCHAR(30) NOT NULL,
	`AuthID` VARCHAR(255) NOT NULL,
	CONSTRAINT `PK_UsersAuthDrivers` PRIMARY KEY (`UserID` ASC, `AuthDriver` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `UsersAuthDrivers` 
 ADD INDEX `IXFK_UsersAuthDrivers_Users` (`UserID` ASC)
;

ALTER TABLE `UsersAuthDrivers` 
 ADD INDEX `IDX_AuthID` (`AuthID` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `UsersAuthDrivers` 
 ADD CONSTRAINT `FK_UsersAuthDrivers_Users`
	FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;