/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:38:48 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RolesAcl_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [RolesAcl] DROP CONSTRAINT [FK_RolesAcl_Roles]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[RolesAcl]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [RolesAcl]
GO

/* Create Tables */

CREATE TABLE [RolesAcl]
(
	[AclID] int NOT NULL IDENTITY (1, 1),
	[Role] varchar(30) NOT NULL,
	[Resource] varchar(100) NOT NULL,
	[Allow] varchar(255) NULL,
	[Deny] varchar(255) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [RolesAcl] 
 ADD CONSTRAINT [PK_RolesAcl]
	PRIMARY KEY CLUSTERED ([AclID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_RolesAcl_Roles] 
 ON [RolesAcl] ([Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_RolesAcl_Resource] 
 ON [RolesAcl] ([Resource] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [RolesAcl] ADD CONSTRAINT [FK_RolesAcl_Roles]
	FOREIGN KEY ([Role]) REFERENCES [Roles] ([Role]) ON DELETE Cascade ON UPDATE Cascade
GO