/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:18:46 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Roles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Roles]
GO

/* Create Tables */

CREATE TABLE [Roles]
(
	[Role] varchar(30) NOT NULL,
	[RoleName] varchar(100) NULL,
	[Description] text NULL,
	[Deleted] tinyint NOT NULL DEFAULT 0
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Roles] 
 ADD CONSTRAINT [PK_Role]
	PRIMARY KEY CLUSTERED ([Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Deleted] 
 ON [Roles] ([Deleted] ASC)
GO