/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:18:46 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Users]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Users]
GO

/* Create Tables */

CREATE TABLE [Users]
(
	[UserID] int NOT NULL IDENTITY (1, 1),
	[FullName] varchar(255) NULL,
	[UserName] varchar(50) NOT NULL,
	[PwHash] varchar(200) NOT NULL,
	[Email] varchar(255) NOT NULL,
	[Phone] varchar(255) NULL,
	[Title] varchar(50) NULL,
	[Language] varchar(50) NULL,
	[Thumbnail] text NULL,
	[PwToken] varchar(255) NULL,
	[PwTokenExpire] datetime2 NULL,
	[Created] datetime2 NULL,
	[LastLogged] datetime2 NULL,
	[Disabled] tinyint NOT NULL DEFAULT 0,
	[Deleted] tinyint NOT NULL DEFAULT 0
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Users] 
 ADD CONSTRAINT [PK_Users]
	PRIMARY KEY CLUSTERED ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Deleted] 
 ON [Users] ([Deleted] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_UserName] 
 ON [Users] ([UserName] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_PwToken] 
 ON [Users] ([PwToken] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Disabled] 
 ON [Users] ([Disabled] ASC)
GO