/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:18:46 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsersAuthDrivers_Users]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsersAuthDrivers] DROP CONSTRAINT [FK_UsersAuthDrivers_Users]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsersAuthDrivers]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsersAuthDrivers]
GO

/* Create Tables */

CREATE TABLE [UsersAuthDrivers]
(
	[UserID] int NOT NULL,
	[AuthDriver] varchar(30) NOT NULL,
	[AuthID] varchar(255) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [UsersAuthDrivers] 
 ADD CONSTRAINT [PK_UsersAuthDrivers]
	PRIMARY KEY CLUSTERED ([UserID] ASC,[AuthDriver] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsersAuthDrivers_Users] 
 ON [UsersAuthDrivers] ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_AuthID] 
 ON [UsersAuthDrivers] ([AuthID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [UsersAuthDrivers] ADD CONSTRAINT [FK_UsersAuthDrivers_Users]
	FOREIGN KEY ([UserID]) REFERENCES [Users] ([UserID]) ON DELETE Cascade ON UPDATE Cascade
GO