/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 20-lis-2016 16:18:46 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsersRole_Users]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsersRoles] DROP CONSTRAINT [FK_UsersRole_Users]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsersRoles_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsersRoles] DROP CONSTRAINT [FK_UsersRoles_Roles]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsersRoles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsersRoles]
GO

/* Create Tables */

CREATE TABLE [UsersRoles]
(
	[UserID] int NOT NULL,
	[Role] varchar(30) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [UsersRoles] 
 ADD CONSTRAINT [PK_UsersRole]
	PRIMARY KEY CLUSTERED ([UserID] ASC,[Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsersRole_Users] 
 ON [UsersRoles] ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsersRoles_Roles] 
 ON [UsersRoles] ([Role] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [UsersRoles] ADD CONSTRAINT [FK_UsersRole_Users]
	FOREIGN KEY ([UserID]) REFERENCES [Users] ([UserID]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [UsersRoles] ADD CONSTRAINT [FK_UsersRoles_Roles]
	FOREIGN KEY ([Role]) REFERENCES [Roles] ([Role]) ON DELETE Cascade ON UPDATE Cascade
GO